package com.gamebroadcast.forum.utils;

import java.security.SecureRandom;
import java.util.Base64;

public abstract class RandomGenerator {
    /**
     * Same length as sessionId generated by Spring Session.
     */
    private static final int TOKEN_LENGTH = 48;

    public static String getRandomToken() {
        byte[] bytes = new byte[TOKEN_LENGTH];
        SecureRandom random = new SecureRandom();
        random.nextBytes(bytes);
        return Base64.getEncoder().encodeToString(bytes);
    }
}
