/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatMessageVM
 */
export interface ChatMessageVM {
    /**
     * 
     * @type {number}
     * @memberof ChatMessageVM
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ChatMessageVM
     */
    authorId?: number;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageVM
     */
    authorName?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageVM
     */
    message?: string;
    /**
     * 
     * @type {Date}
     * @memberof ChatMessageVM
     */
    publishDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageVM
     */
    profilePicturePath?: string;
}

export function ChatMessageVMFromJSON(json: any): ChatMessageVM {
    return ChatMessageVMFromJSONTyped(json, false);
}

export function ChatMessageVMFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessageVM {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'authorId': !exists(json, 'authorId') ? undefined : json['authorId'],
        'authorName': !exists(json, 'authorName') ? undefined : json['authorName'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'publishDate': !exists(json, 'publishDate') ? undefined : (new Date(json['publishDate'])),
        'profilePicturePath': !exists(json, 'profilePicturePath') ? undefined : json['profilePicturePath'],
    };
}

export function ChatMessageVMToJSON(value?: ChatMessageVM | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'authorId': value.authorId,
        'authorName': value.authorName,
        'message': value.message,
        'publishDate': value.publishDate === undefined ? undefined : (value.publishDate.toISOString()),
        'profilePicturePath': value.profilePicturePath,
    };
}

