/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentVM
 */
export interface CommentVM {
    /**
     * 
     * @type {number}
     * @memberof CommentVM
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof CommentVM
     */
    articleId?: number;
    /**
     * 
     * @type {number}
     * @memberof CommentVM
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof CommentVM
     */
    content?: string;
}

export function CommentVMFromJSON(json: any): CommentVM {
    return CommentVMFromJSONTyped(json, false);
}

export function CommentVMFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentVM {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'articleId': !exists(json, 'articleId') ? undefined : json['articleId'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'content': !exists(json, 'content') ? undefined : json['content'],
    };
}

export function CommentVMToJSON(value?: CommentVM | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'articleId': value.articleId,
        'userId': value.userId,
        'content': value.content,
    };
}

