/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GameVM
 */
export interface GameVM {
    /**
     * 
     * @type {number}
     * @memberof GameVM
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GameVM
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof GameVM
     */
    path?: string;
    /**
     * 
     * @type {Date}
     * @memberof GameVM
     */
    publishDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof GameVM
     */
    authorName?: string;
}

export function GameVMFromJSON(json: any): GameVM {
    return GameVMFromJSONTyped(json, false);
}

export function GameVMFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameVM {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'publishDate': !exists(json, 'publishDate') ? undefined : (new Date(json['publishDate'])),
        'authorName': !exists(json, 'authorName') ? undefined : json['authorName'],
    };
}

export function GameVMToJSON(value?: GameVM | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'path': value.path,
        'publishDate': value.publishDate === undefined ? undefined : (value.publishDate.toISOString()),
        'authorName': value.authorName,
    };
}

