/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LikeVM
 */
export interface LikeVM {
    /**
     * 
     * @type {number}
     * @memberof LikeVM
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof LikeVM
     */
    articleId?: number;
    /**
     * 
     * @type {number}
     * @memberof LikeVM
     */
    userId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof LikeVM
     */
    isLike?: boolean;
}

export function LikeVMFromJSON(json: any): LikeVM {
    return LikeVMFromJSONTyped(json, false);
}

export function LikeVMFromJSONTyped(json: any, ignoreDiscriminator: boolean): LikeVM {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'articleId': !exists(json, 'articleId') ? undefined : json['articleId'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'isLike': !exists(json, 'isLike') ? undefined : json['isLike'],
    };
}

export function LikeVMToJSON(value?: LikeVM | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'articleId': value.articleId,
        'userId': value.userId,
        'isLike': value.isLike,
    };
}

