/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCredentialsUpdate
 */
export interface UserCredentialsUpdate {
    /**
     * 
     * @type {string}
     * @memberof UserCredentialsUpdate
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserCredentialsUpdate
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserCredentialsUpdate
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof UserCredentialsUpdate
     */
    shortDescription?: string;
}

export function UserCredentialsUpdateFromJSON(json: any): UserCredentialsUpdate {
    return UserCredentialsUpdateFromJSONTyped(json, false);
}

export function UserCredentialsUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCredentialsUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': !exists(json, 'username') ? undefined : json['username'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'shortDescription': !exists(json, 'shortDescription') ? undefined : json['shortDescription'],
    };
}

export function UserCredentialsUpdateToJSON(value?: UserCredentialsUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'email': value.email,
        'password': value.password,
        'shortDescription': value.shortDescription,
    };
}

