/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthorVM
 */
export interface AuthorVM {
    /**
     * 
     * @type {number}
     * @memberof AuthorVM
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AuthorVM
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorVM
     */
    shortDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorVM
     */
    profilePicturePath?: string;
}

export function AuthorVMFromJSON(json: any): AuthorVM {
    return AuthorVMFromJSONTyped(json, false);
}

export function AuthorVMFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorVM {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'shortDescription': !exists(json, 'shortDescription') ? undefined : json['shortDescription'],
        'profilePicturePath': !exists(json, 'profilePicturePath') ? undefined : json['profilePicturePath'],
    };
}

export function AuthorVMToJSON(value?: AuthorVM | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'shortDescription': value.shortDescription,
        'profilePicturePath': value.profilePicturePath,
    };
}

