/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GameSearchInfoVM
 */
export interface GameSearchInfoVM {
    /**
     * 
     * @type {number}
     * @memberof GameSearchInfoVM
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GameSearchInfoVM
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof GameSearchInfoVM
     */
    path?: string;
    /**
     * 
     * @type {Date}
     * @memberof GameSearchInfoVM
     */
    publishDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof GameSearchInfoVM
     */
    authorName?: string;
    /**
     * 
     * @type {string}
     * @memberof GameSearchInfoVM
     */
    introduction?: string;
    /**
     * 
     * @type {number}
     * @memberof GameSearchInfoVM
     */
    meanUserScore?: number;
    /**
     * 
     * @type {string}
     * @memberof GameSearchInfoVM
     */
    developer?: string;
    /**
     * 
     * @type {number}
     * @memberof GameSearchInfoVM
     */
    editorScore?: number;
    /**
     * 
     * @type {number}
     * @memberof GameSearchInfoVM
     */
    popularity?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof GameSearchInfoVM
     */
    genres?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GameSearchInfoVM
     */
    platforms?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GameSearchInfoVM
     */
    distributions?: Array<string>;
}

export function GameSearchInfoVMFromJSON(json: any): GameSearchInfoVM {
    return GameSearchInfoVMFromJSONTyped(json, false);
}

export function GameSearchInfoVMFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameSearchInfoVM {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'publishDate': !exists(json, 'publishDate') ? undefined : (new Date(json['publishDate'])),
        'authorName': !exists(json, 'authorName') ? undefined : json['authorName'],
        'introduction': !exists(json, 'introduction') ? undefined : json['introduction'],
        'meanUserScore': !exists(json, 'meanUserScore') ? undefined : json['meanUserScore'],
        'developer': !exists(json, 'developer') ? undefined : json['developer'],
        'editorScore': !exists(json, 'editorScore') ? undefined : json['editorScore'],
        'popularity': !exists(json, 'popularity') ? undefined : json['popularity'],
        'genres': !exists(json, 'genres') ? undefined : json['genres'],
        'platforms': !exists(json, 'platforms') ? undefined : json['platforms'],
        'distributions': !exists(json, 'distributions') ? undefined : json['distributions'],
    };
}

export function GameSearchInfoVMToJSON(value?: GameSearchInfoVM | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'path': value.path,
        'publishDate': value.publishDate === undefined ? undefined : (value.publishDate.toISOString()),
        'authorName': value.authorName,
        'introduction': value.introduction,
        'meanUserScore': value.meanUserScore,
        'developer': value.developer,
        'editorScore': value.editorScore,
        'popularity': value.popularity,
        'genres': value.genres,
        'platforms': value.platforms,
        'distributions': value.distributions,
    };
}

