/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AuthorVM,
    AuthorVMFromJSON,
    AuthorVMFromJSONTyped,
    AuthorVMToJSON,
} from './AuthorVM';
import {
    CommentVM,
    CommentVMFromJSON,
    CommentVMFromJSONTyped,
    CommentVMToJSON,
} from './CommentVM';
import {
    ReviewVM,
    ReviewVMFromJSON,
    ReviewVMFromJSONTyped,
    ReviewVMToJSON,
} from './ReviewVM';

/**
 * 
 * @export
 * @interface GameFullInfoVM
 */
export interface GameFullInfoVM {
    /**
     * 
     * @type {number}
     * @memberof GameFullInfoVM
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GameFullInfoVM
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof GameFullInfoVM
     */
    introduction?: string;
    /**
     * 
     * @type {string}
     * @memberof GameFullInfoVM
     */
    path?: string;
    /**
     * 
     * @type {Date}
     * @memberof GameFullInfoVM
     */
    publishDate?: Date;
    /**
     * 
     * @type {AuthorVM}
     * @memberof GameFullInfoVM
     */
    author?: AuthorVM;
    /**
     * 
     * @type {number}
     * @memberof GameFullInfoVM
     */
    likes?: number;
    /**
     * 
     * @type {number}
     * @memberof GameFullInfoVM
     */
    dislikes?: number;
    /**
     * 
     * @type {Array<CommentVM>}
     * @memberof GameFullInfoVM
     */
    comments?: Array<CommentVM>;
    /**
     * 
     * @type {Date}
     * @memberof GameFullInfoVM
     */
    gamePublishDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof GameFullInfoVM
     */
    developer?: string;
    /**
     * 
     * @type {number}
     * @memberof GameFullInfoVM
     */
    editorScore?: number;
    /**
     * 
     * @type {number}
     * @memberof GameFullInfoVM
     */
    userScore?: number;
    /**
     * 
     * @type {Array<ReviewVM>}
     * @memberof GameFullInfoVM
     */
    reviews?: Array<ReviewVM>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GameFullInfoVM
     */
    genres?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GameFullInfoVM
     */
    platforms?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GameFullInfoVM
     */
    distributions?: Array<string>;
}

export function GameFullInfoVMFromJSON(json: any): GameFullInfoVM {
    return GameFullInfoVMFromJSONTyped(json, false);
}

export function GameFullInfoVMFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameFullInfoVM {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'introduction': !exists(json, 'introduction') ? undefined : json['introduction'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'publishDate': !exists(json, 'publishDate') ? undefined : (new Date(json['publishDate'])),
        'author': !exists(json, 'author') ? undefined : AuthorVMFromJSON(json['author']),
        'likes': !exists(json, 'likes') ? undefined : json['likes'],
        'dislikes': !exists(json, 'dislikes') ? undefined : json['dislikes'],
        'comments': !exists(json, 'comments') ? undefined : ((json['comments'] as Array<any>).map(CommentVMFromJSON)),
        'gamePublishDate': !exists(json, 'gamePublishDate') ? undefined : (new Date(json['gamePublishDate'])),
        'developer': !exists(json, 'developer') ? undefined : json['developer'],
        'editorScore': !exists(json, 'editorScore') ? undefined : json['editorScore'],
        'userScore': !exists(json, 'userScore') ? undefined : json['userScore'],
        'reviews': !exists(json, 'reviews') ? undefined : ((json['reviews'] as Array<any>).map(ReviewVMFromJSON)),
        'genres': !exists(json, 'genres') ? undefined : json['genres'],
        'platforms': !exists(json, 'platforms') ? undefined : json['platforms'],
        'distributions': !exists(json, 'distributions') ? undefined : json['distributions'],
    };
}

export function GameFullInfoVMToJSON(value?: GameFullInfoVM | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'introduction': value.introduction,
        'path': value.path,
        'publishDate': value.publishDate === undefined ? undefined : (value.publishDate.toISOString()),
        'author': AuthorVMToJSON(value.author),
        'likes': value.likes,
        'dislikes': value.dislikes,
        'comments': value.comments === undefined ? undefined : ((value.comments as Array<any>).map(CommentVMToJSON)),
        'gamePublishDate': value.gamePublishDate === undefined ? undefined : (value.gamePublishDate.toISOString()),
        'developer': value.developer,
        'editorScore': value.editorScore,
        'userScore': value.userScore,
        'reviews': value.reviews === undefined ? undefined : ((value.reviews as Array<any>).map(ReviewVMToJSON)),
        'genres': value.genres,
        'platforms': value.platforms,
        'distributions': value.distributions,
    };
}

