/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LikeAdd
 */
export interface LikeAdd {
    /**
     * 
     * @type {number}
     * @memberof LikeAdd
     */
    contentId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof LikeAdd
     */
    isLike?: boolean;
}

export function LikeAddFromJSON(json: any): LikeAdd {
    return LikeAddFromJSONTyped(json, false);
}

export function LikeAddFromJSONTyped(json: any, ignoreDiscriminator: boolean): LikeAdd {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contentId': !exists(json, 'contentId') ? undefined : json['contentId'],
        'isLike': !exists(json, 'isLike') ? undefined : json['isLike'],
    };
}

export function LikeAddToJSON(value?: LikeAdd | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contentId': value.contentId,
        'isLike': value.isLike,
    };
}

