/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingUpdate
 */
export interface RatingUpdate {
    /**
     * 
     * @type {number}
     * @memberof RatingUpdate
     */
    value?: number;
}

export function RatingUpdateFromJSON(json: any): RatingUpdate {
    return RatingUpdateFromJSONTyped(json, false);
}

export function RatingUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function RatingUpdateToJSON(value?: RatingUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}

