/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewAdd
 */
export interface ReviewAdd {
    /**
     * 
     * @type {string}
     * @memberof ReviewAdd
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewAdd
     */
    introduction?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewAdd
     */
    content?: string;
    /**
     * 
     * @type {number}
     * @memberof ReviewAdd
     */
    score?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ReviewAdd
     */
    pluses?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ReviewAdd
     */
    minuses?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ReviewAdd
     */
    gameId?: number;
}

export function ReviewAddFromJSON(json: any): ReviewAdd {
    return ReviewAddFromJSONTyped(json, false);
}

export function ReviewAddFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewAdd {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'introduction': !exists(json, 'introduction') ? undefined : json['introduction'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'score': !exists(json, 'score') ? undefined : json['score'],
        'pluses': !exists(json, 'pluses') ? undefined : json['pluses'],
        'minuses': !exists(json, 'minuses') ? undefined : json['minuses'],
        'gameId': !exists(json, 'gameId') ? undefined : json['gameId'],
    };
}

export function ReviewAddToJSON(value?: ReviewAdd | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'introduction': value.introduction,
        'content': value.content,
        'score': value.score,
        'pluses': value.pluses,
        'minuses': value.minuses,
        'gameId': value.gameId,
    };
}

