INSERT INTO app_user (id, username, email, password, profile_picture_path, short_description, role, enabled, locked, last_used) VALUES (nextval('user_sequence'), 'a', 'a@user.com', '$2a$12$Sze0MTTDf1ySwSeQ6yllyeQZawfEC/iBddWcDPhHOGawKsAmAsGPq', 'ODM5NDFj', 'Żądzę wszystkimi i wszystkim! Muahaha', 'ADMIN', TRUE, FALSE, '1995-11-08 06:14:00.742000000')
INSERT INTO app_user (id, username, email, password, profile_picture_path, short_description, role, enabled, locked, last_used) VALUES (nextval('user_sequence'), 'b', 'b@user.com', '$2a$12$Sze0MTTDf1ySwSeQ6yllyeQZawfEC/iBddWcDPhHOGawKsAmAsGPq', 'N2EzYzhh', 'Jestem pierwszym edytorem tego portalu. Składajcie pokłony!', 'EDITOR', TRUE, FALSE, '1995-11-27 06:14:00.742000000')
INSERT INTO app_user (id, username, email, password, profile_picture_path, short_description, role, enabled, locked, last_used) VALUES (nextval('user_sequence'), 'c', 'c@user.com', '$2a$12$Sze0MTTDf1ySwSeQ6yllyeQZawfEC/iBddWcDPhHOGawKsAmAsGPq', 'MmNmMjFm', 'Moje hobby to pisanie ciekawych artykułów, recenzjonowanie gier oraz granie w nie przy ciepłym kubku mojej kochanej porannej kawusi. Jeżeli lubisz to co piszę, zostaw likea!', 'EDITOR', FALSE, FALSE, '1997-06-17 06:14:00.742000000')
INSERT INTO app_user (id, username, email, password, profile_picture_path, short_description, role, enabled, locked, last_used) VALUES (nextval('user_sequence'), 'd', 'd@user.com', '$2a$12$Sze0MTTDf1ySwSeQ6yllyeQZawfEC/iBddWcDPhHOGawKsAmAsGPq', 'NGE3OTRl', 'Idź do redakcji o grach mówili, będziesz dobrze zarabiać mówili...', 'EDITOR', TRUE, TRUE, '2001-09-11 06:14:00.742000000')

INSERT INTO app_user (id, username, email, password, profile_picture_path, short_description, role, enabled, locked, last_used) VALUES (nextval('user_sequence'), 'Cebullanka y Grzanka', 'cebullanka@onet.pl', '$2a$12$Z66wr4ZOg2HgbEyr./ysLOoLbPwAkti88IJVKJt3LRczjVxlGoWcm', 'NGE3OTRl', 'Są rzeczy których nie ma', 'USER', TRUE, FALSE, '2021-02-25 06:14:00.742000000')
INSERT INTO app_user (id, username, email, password, profile_picture_path, short_description, role, enabled, locked, last_used) VALUES (nextval('user_sequence'), 'mateomateowy', 'mm@zabawa.pl', '$2a$12$e5gFkN5rBOFFxAihp8Zo1uUFwpDpnDT/PSXLgawg.BPCmvZXPSm2C', 'NzRjZjM1', 'Lubię gry, gitarę i książki', 'USER', TRUE, FALSE, '2022-04-14 06:14:00.742000000')
INSERT INTO app_user (id, username, email, password, profile_picture_path, short_description, role, enabled, locked, last_used) VALUES (nextval('user_sequence'), 'ksiunszka', 'kasia@kwiatek.com', '$2a$12$mRYcud/CfZhw0iJ42QkfS.8oriet7WtYuR30fXHsvCY53ZZBtrie2', 'NWE2NWU4', 'Cześć kochani! Jestem Kasia, mam 12 lat i uwielbiam Simsy. Robię różne domki i nadaję Simom fajne imionka!', 'USER', TRUE, FALSE, '2022-04-12 06:14:00.742000000')
INSERT INTO app_user (id, username, email, password, profile_picture_path, short_description, role, enabled, locked, last_used) VALUES (nextval('user_sequence'), 'barbarara', 'brb@bump.up', '$2a$12$bdjxiww20dyijaKxqrg8YuX6zZxnmvsXfHooV4vWSbkjenk6UacTS', 'MjIzNzM0', 'Emogirl, instagram person, aestetic vibes', 'USER', TRUE, FALSE, '2022-02-13 06:14:00.742000000')
INSERT INTO app_user (id, username, email, password, profile_picture_path, short_description, role, enabled, locked, last_used) VALUES (nextval('user_sequence'), 'tomorrow', 'txt@usasa.com', '$2a$12$DVQYbI9/xt3QCF7bEDE8J.telOvgKTj1LflIO5F7BlSIPQ3IeEUMe', 'YzcyMzcz', 'GTA, Mortal Combat, Wiedźmin 3, Skyrim. Chcesz grać napisz w chacie 😊', 'USER', TRUE, FALSE, '2022-04-02 06:14:00.742000000')
INSERT INTO app_user (id, username, email, password, profile_picture_path, short_description, role, enabled, locked, last_used) VALUES (nextval('user_sequence'), 'mAjKeL', 'majkel@zal.pl', '$2a$12$InNJFnxOAXbTn48iVUDWT.xfQ5BQWvUnAvoqHAzK30o3TSs9puJYW', 'MDgyNzIz', 'WiTaM z TeJ sTrOnY mIkAeL jEsLi LuBiSz GtA nApIsZ kOtLeT w cHAcie a DoDaM cIe Do ZnAjOmYcH nA fB', 'USER', TRUE, FALSE, '2022-04-05 06:14:00.742000000')
INSERT INTO app_user (id, username, email, password, profile_picture_path, short_description, role, enabled, locked, last_used) VALUES (nextval('user_sequence'), 'dramione', 'drama@wtopa.pl', '$2a$12$JUvqgQdRNhG/9E1Cg60V3uNKJmRUevEBoVlT95Jhj/zA4f7cOv7AK', 'Mzg0MWUz', 'Paula, 15 lat. Fanka shipu Draco i Hermiony. Już nie mogę się doczekać nowej gry o Hogwarcie!!!!', 'USER', TRUE, FALSE, '2022-03-27 06:14:00.742000000')
INSERT INTO app_user (id, username, email, password, profile_picture_path, short_description, role, enabled, locked, last_used) VALUES (nextval('user_sequence'), 'Darkboy64', 'darek@wp.pl', '$2a$12$NiSWspCtiqoBZHuj5ECjnuUROIrP/zHHSahcpcUzdWws9f.5gD1Ce', 'MWNlNGY0', 'Drżyjcie ofiary! Przed wami najwyższy król cienia DARK! Nie wchodź mi w drogę bo inaczej zły będzie twój los! A jeśli chcesz pograć zapraszam na LoLa 😊', 'USER', TRUE, FALSE, '2009-11-21 06:14:00.742000000')
INSERT INTO app_user (id, username, email, password, profile_picture_path, short_description, role, enabled, locked, last_used) VALUES (nextval('user_sequence'), 'theguiltyone', 'theguiltyone@innocence.lt', '$2a$12$HPudPl3a.YG8l0DceTD1B.fesyMHl841bRD82lGyVDJVgHnyfNW1m', 'MmQ5M2Rk', 'Gdziekolwiek się znajdę, to ja jestem winny...', 'USER', TRUE, FALSE, '2022-04-13 06:14:00.742000000')
INSERT INTO app_user (id, username, email, password, profile_picture_path, short_description, role, enabled, locked, last_used) VALUES (nextval('user_sequence'), 'AjgorPL', 'ajgor@onet.pl', '$2a$12$nFn19zzvo27N9P9aazuq7upWOp2ZyeP5FT7KH4HP4JF0gwyehEAIy', 'OWM4MTlj', 'Każda gra ma wady, i bugi, a ja je znajdę.', 'USER', TRUE, FALSE, '2022-03-30 06:14:00.742000000')

INSERT INTO content (id, title, introduction, path, author_id, publish_date, dtype) VALUES (nextval('content_sequence'), 'Top 10 drzwi w grach', 'Wszyscy kochamy drzwi: obrotowe, drewniane, wybuchające. Jednak 10 z nich na zawsze zapadło nam w pamięci.', 'MTVlYzEw', 2, '2014-11-07 06:14:00.742000000', 'A')
INSERT INTO content (id, title, introduction, path, author_id, publish_date, dtype) VALUES (nextval('content_sequence'), 'Kraby w grach', 'iiiiiiiiiiiiiiiii', 'NTA5NGRi', 3, '2017-12-24 06:14:00.742000000', 'A')
INSERT INTO content (id, title, introduction, path, author_id, publish_date, dtype) VALUES (nextval('content_sequence'), 'Czy Dying Light 2 spełniło oczekiwnia?', 'iiiiiiiiiiiii', 'NGM2Yjcz', 3, '2007-05-14 06:14:00.742000000', 'A')
INSERT INTO content (id, title, introduction, path, author_id, publish_date, dtype) VALUES (nextval('content_sequence'), 'Kiedy Wiedźmin 4?', 'iiiiiiiiiiiiiiiii', 'YzFiZTkw', 4, '1997-04-01 06:14:00.742000000', 'A')
INSERT INTO content (id, title, introduction, path, author_id, publish_date, dtype) VALUES (nextval('content_sequence'), 'Dlaczego GTA 6 nigdy nie powstanie', 'iiiiiiiiiiiiiiiii', 'OTVkYWU5', 2, '2021-09-17 06:14:00.742000000', 'A')
-- INSERT INTO content (id, title, introduction, path, author_id, publish_date, dtype) VALUES (nextval('content_sequence'), 'Dlaczego GTA 6 nigdy nie powstanie', 'iiiiiiiiiiiiiiiii', 'YjUxZDZi', 2, '2022-08-27 06:14:00.742000000', 'A')

INSERT INTO content (id, title, introduction, path, author_id, publish_date, game_publish_date, developer, editor_score, dtype) VALUES (nextval('content_sequence'), 'GTA V', 'Taka gra, że się strzela i jeździ i parodiuje ameryke', 'MWU2NTU1', '1', '2013-09-17', '2013-09-17', 'Rockstar', 4.5, 'G')
-- INSERT INTO content (id, title, introduction, path, author_id, publish_date, game_publish_date, developer, editor_score, dtype) VALUES (nextval('content_sequence'), 'GTA V', 'Taka gra, że się strzela i jeździ i parodiuje ameryke', 'NWFjY2E0', '1', '2013-09-17', '2013-09-17', 'Rockstar', 4.5, 'G')
-- INSERT INTO content (id, title, introduction, path, author_id, publish_date, game_publish_date, developer, editor_score, dtype) VALUES (nextval('content_sequence'), 'GTA V', 'Taka gra, że się strzela i jeździ i parodiuje ameryke', 'NzRiZDYx', '1', '2013-09-17', '2013-09-17', 'Rockstar', 4.5, 'G')
-- INSERT INTO content (id, title, introduction, path, author_id, publish_date, game_publish_date, developer, editor_score, dtype) VALUES (nextval('content_sequence'), 'GTA V', 'Taka gra, że się strzela i jeździ i parodiuje ameryke', 'YmU4OGRj', '1', '2013-09-17', '2013-09-17', 'Rockstar', 4.5, 'G')
-- INSERT INTO content (id, title, introduction, path, author_id, publish_date, game_publish_date, developer, editor_score, dtype) VALUES (nextval('content_sequence'), 'GTA V', 'Taka gra, że się strzela i jeździ i parodiuje ameryke', 'ZGZkM2Nk', '1', '2013-09-17', '2013-09-17', 'Rockstar', 4.5, 'G')

-- INSERT INTO content (id, title, introduction, path, author_id, publish_date, score, dtype) VALUES (nextval('content_sequence'), 'GTA V', 'Taka gra, że się strzela i jeździ i parodiuje ameryke', 'YzU1YTA3', 1, '2013-09-17', 4.5, 'G')
-- INSERT INTO content (id, title, introduction, path, author_id, publish_date, score, dtype) VALUES (nextval('content_sequence'), 'GTA V', 'Taka gra, że się strzela i jeździ i parodiuje ameryke', 'ZGEwNzk4', 1, '2013-09-17', 4.5, 'G')
-- INSERT INTO content (id, title, introduction, path, author_id, publish_date, score, dtype) VALUES (nextval('content_sequence'), 'GTA V', 'Taka gra, że się strzela i jeździ i parodiuje ameryke', 'MGVmNjc3', 1, '2013-09-17', 4.5, 'G')
-- INSERT INTO content (id, title, introduction, path, author_id, publish_date, score, dtype) VALUES (nextval('content_sequence'), 'GTA V', 'Taka gra, że się strzela i jeździ i parodiuje ameryke', 'ZGEzYTY4', 1, '2013-09-17', 4.5, 'G')

INSERT INTO rating(id, value, author_id, game_id) VALUES(nextval('rating_sequence'), 9.7, 6, 7)
INSERT INTO rating(id, value, author_id, game_id) VALUES(nextval('rating_sequence'), 7.4, 11, 7)
INSERT INTO rating(id, value, author_id, game_id) VALUES(nextval('rating_sequence'), 8.5, 13, 7)
INSERT INTO rating(id, value, author_id, game_id) VALUES(nextval('rating_sequence'), 3.9, 1, 8)
INSERT INTO rating(id, value, author_id, game_id) VALUES(nextval('rating_sequence'), 5.1, 4, 8)
INSERT INTO rating(id, value, author_id, game_id) VALUES(nextval('rating_sequence'), 7.8, 9, 8)
INSERT INTO rating(id, value, author_id, game_id) VALUES(nextval('rating_sequence'), 4.5, 1, 9)
INSERT INTO rating(id, value, author_id, game_id) VALUES(nextval('rating_sequence'), 8.1, 13, 9)
INSERT INTO rating(id, value, author_id, game_id) VALUES(nextval('rating_sequence'), 4.8, 1, 10)
INSERT INTO rating(id, value, author_id, game_id) VALUES(nextval('rating_sequence'), 7.4, 2, 10)
INSERT INTO rating(id, value, author_id, game_id) VALUES(nextval('rating_sequence'), 3.4, 3, 10)
INSERT INTO rating(id, value, author_id, game_id) VALUES(nextval('rating_sequence'), 9.6, 9, 10)
INSERT INTO rating(id, value, author_id, game_id) VALUES(nextval('rating_sequence'), 2.4, 11, 10)

--INSERT INTO content_ratings (game_id, ratings_id) VALUES (1, 1)

--INSERT INTO game_distributions (game_id, distributions) VALUES (1, 'Steam')

--INSERT INTO game_genres (game_id, genres) VALUES (1, 'Strategy')

--INSERT INTO game_platforms (game_id, platforms) VALUES (1, 'PC')

--INSERT INTO review_pluses (review_id, pluses) VALUES (5, 'Ładna grafika, Dobre fps')

--INSERT INTO review_minuses (review_id, minuses) VALUES (5, 'Brzydka grafika', 'Niskie fpsy')

INSERT INTO likes (id, content_id, author_id, is_like) VALUES (nextval('like_sequence'), 1, 2, TRUE)
INSERT INTO likes (id, content_id, author_id, is_like) VALUES (nextval('like_sequence'), 1, 1, TRUE)
INSERT INTO likes (id, content_id, author_id, is_like) VALUES (nextval('like_sequence'), 1, 3, FALSE)
INSERT INTO likes (id, content_id, author_id, is_like) VALUES (nextval('like_sequence'), 2, 1, TRUE)
INSERT INTO likes (id, content_id, author_id, is_like) VALUES (nextval('like_sequence'), 3, 2, TRUE)
INSERT INTO likes (id, content_id, author_id, is_like) VALUES (nextval('like_sequence'), 4, 3, TRUE)

INSERT INTO comments (id, content_id, author_id, comment) VALUES (nextval('comment_sequence'), 1, 4, 'Animacje otwierania drzwi w RE Remaster UwU')
INSERT INTO comments (id, content_id, author_id, comment) VALUES (nextval('comment_sequence'), 1, 3, 'Czy autor tekstu zdał mature z polskiego?!?!')
INSERT INTO comments (id, content_id, author_id, comment) VALUES (nextval('comment_sequence'), 1, 2, 'Mógłbym godzinami otweriać i zamykać drzwi')
INSERT INTO comments (id, content_id, author_id, comment) VALUES (nextval('comment_sequence'), 2, 1, 'I''ll have 2 Number 9s, a number 9 large, number 6 with extra dip, number 7, 2 number 45s, one with cheese, and a large soda.')
INSERT INTO comments (id, content_id, author_id, comment) VALUES (nextval('comment_sequence'), 2, 3, 'Od san andreas to już nie to samo')
INSERT INTO comments (id, content_id, author_id, comment) VALUES (nextval('comment_sequence'), 3, 1, 'Kiedyś krab złamał mi palec')

-- INSERT INTO comments (id, content_id, author_id, content) VALUES (nextval('comment_sequence'), 6, 1, 'Kiedyś krab złamał mi palec')
