/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    GameAddUpdate,
    GameAddUpdateFromJSON,
    GameAddUpdateToJSON,
    GameFullInfoVM,
    GameFullInfoVMFromJSON,
    GameFullInfoVMToJSON,
    GameVM,
    GameVMFromJSON,
    GameVMToJSON,
} from '../models';

export interface AddGameRequest {
    gameAddUpdate: GameAddUpdate;
}

export interface DeleteGameRequest {
    gameId: number;
}

export interface GetAllGames1Request {
    gameId: number;
}

export interface GetGameRequest {
    gameId: number;
}

export interface GetGameFullInfoRequest {
    gameId: number;
}

export interface UpdateGameRequest {
    gameId: number;
    gameAddUpdate: GameAddUpdate;
}

/**
 * 
 */
export class GameControllerApi extends runtime.BaseAPI {

    /**
     */
    async addGameRaw(requestParameters: AddGameRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.gameAddUpdate === null || requestParameters.gameAddUpdate === undefined) {
            throw new runtime.RequiredError('gameAddUpdate','Required parameter requestParameters.gameAddUpdate was null or undefined when calling addGame.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/game`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GameAddUpdateToJSON(requestParameters.gameAddUpdate),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async addGame(requestParameters: AddGameRequest, initOverrides?: RequestInit): Promise<void> {
        await this.addGameRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteGameRaw(requestParameters: DeleteGameRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.gameId === null || requestParameters.gameId === undefined) {
            throw new runtime.RequiredError('gameId','Required parameter requestParameters.gameId was null or undefined when calling deleteGame.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/game/{gameId}`.replace(`{${"gameId"}}`, encodeURIComponent(String(requestParameters.gameId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteGame(requestParameters: DeleteGameRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteGameRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getAllGamesRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<GameVM>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/game`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GameVMFromJSON));
    }

    /**
     */
    async getAllGames(initOverrides?: RequestInit): Promise<Array<GameVM>> {
        const response = await this.getAllGamesRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getAllGames1Raw(requestParameters: GetAllGames1Request, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<GameVM>>> {
        if (requestParameters.gameId === null || requestParameters.gameId === undefined) {
            throw new runtime.RequiredError('gameId','Required parameter requestParameters.gameId was null or undefined when calling getAllGames1.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/game/Similar/{gameId}`.replace(`{${"gameId"}}`, encodeURIComponent(String(requestParameters.gameId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GameVMFromJSON));
    }

    /**
     */
    async getAllGames1(requestParameters: GetAllGames1Request, initOverrides?: RequestInit): Promise<Array<GameVM>> {
        const response = await this.getAllGames1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getGameRaw(requestParameters: GetGameRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<GameVM>> {
        if (requestParameters.gameId === null || requestParameters.gameId === undefined) {
            throw new runtime.RequiredError('gameId','Required parameter requestParameters.gameId was null or undefined when calling getGame.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/game/{gameId}`.replace(`{${"gameId"}}`, encodeURIComponent(String(requestParameters.gameId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameVMFromJSON(jsonValue));
    }

    /**
     */
    async getGame(requestParameters: GetGameRequest, initOverrides?: RequestInit): Promise<GameVM> {
        const response = await this.getGameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getGameFullInfoRaw(requestParameters: GetGameFullInfoRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<GameFullInfoVM>> {
        if (requestParameters.gameId === null || requestParameters.gameId === undefined) {
            throw new runtime.RequiredError('gameId','Required parameter requestParameters.gameId was null or undefined when calling getGameFullInfo.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/game/FullInfo/{gameId}`.replace(`{${"gameId"}}`, encodeURIComponent(String(requestParameters.gameId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameFullInfoVMFromJSON(jsonValue));
    }

    /**
     */
    async getGameFullInfo(requestParameters: GetGameFullInfoRequest, initOverrides?: RequestInit): Promise<GameFullInfoVM> {
        const response = await this.getGameFullInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateGameRaw(requestParameters: UpdateGameRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.gameId === null || requestParameters.gameId === undefined) {
            throw new runtime.RequiredError('gameId','Required parameter requestParameters.gameId was null or undefined when calling updateGame.');
        }

        if (requestParameters.gameAddUpdate === null || requestParameters.gameAddUpdate === undefined) {
            throw new runtime.RequiredError('gameAddUpdate','Required parameter requestParameters.gameAddUpdate was null or undefined when calling updateGame.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/game/{gameId}`.replace(`{${"gameId"}}`, encodeURIComponent(String(requestParameters.gameId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: GameAddUpdateToJSON(requestParameters.gameAddUpdate),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateGame(requestParameters: UpdateGameRequest, initOverrides?: RequestInit): Promise<void> {
        await this.updateGameRaw(requestParameters, initOverrides);
    }

}
